export enum ToastType {
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  CART_SUCCESS = 'CART_SUCCESS',
  CREATE_SUCCESS = 'CREATE_SUCCESS',
  READ_SUCCESS = 'READ_SUCCESS',
  UPDATE_SUCCESS = 'UPDATE_SUCCESS',
  DELETE_SUCCESS = 'DELETE_SUCCESS',
  ERROR = 'ERROR',
}
